const str = 'MT.name'
const strA = 'MT.address'
const str_ = 'T.zname'
const str_zh7 = 'zh7'
const str_zh8 = 'zh8'

const str2 = 'E.a'
const str3 = 'E.b.c.d'
const str3_ = 'E.b.c.e'
const str4 = 'T.name'
const str5 = 'T.u_name'
