name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Node.js modules
        run: npm install

      - name: Lint
        run: npm run lint

      - name: VSCE Packge
        run: npx vsce package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_number }}
          release_name: Release ${{ github.ref }}
          body: New Release.
          draft: false
          prerelease: false
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: NameOfYourArtifact.exe
          asset_name: NameOfYourArtifact.exe
          asset_content_type: application/octet-stream